### ISSUE TITLE
Need to upgrade to bdk 0.17

### ISSUE THREAD

**Issue by notmandatory** [weareseba/bdk-reserves#4]
I had to temporarily comment out the bdk-reserves tests in https://github.com/bitcoindevkit/bdk-cli/pull/73. Please make a new release of this project with bdk 0.17 and then we can re-enable those tests.  The issue is that `bdk-reserves` and `bdk-cli` need to be using the same version of `bdk`.

**Comment by ulrichard** [comment]
Hi @notmandatory  I just released bdk-reserves 0.17
I also started adapting the relevant parts of bdk-cli base on your branch. But I can only do this with low priority, so maybe you are quicker with that.

**Comment by notmandatory** [comment]
Thanks for the updated `bdk-reserves` 0.17.  I'll take a crack at updating the `bdk-cli` with it for the next release.
